### ISSUE TITLE
What's the current state of this library?

### ISSUE THREAD

**Issue by theofidry** [qandidate-labs/stack-request-id#11]
There is not much activity, the Travis config is outdated and there is no stable release, so I'm just wondering if this library is just stable or if this is completely abandoned?

**Comment by wjzijderveld** [comment]
We still use it in production. I'll try to take a look this evening, to update some Travis config and possibly create a release

**Comment by theofidry** [comment]
Thanks, that's all I needed to know :)

That said I think it could be simplified by something along the lines of:

```php
use Ramsey\Uuid\Uuid;

final class RequestIdProcessor
{
    private $requestId;

    public function __construct()
    {
        $this->requestId = Uuid::uuid4()->toString();
    }

    public function __invoke(array $record)
    {
        $record['extra']['request_id'] = $this->requestId;

        return $record;
    }
}
```

That assumes you don't actually need the request ID in your code.

**Comment by othillo** [comment]
The idea of the MonologProcessor is that it picks up the uuid from the headers and not that it creates a uuid itself. This way you can have your webserver or a http client generate a uuid, pass it along and log it in your application.

My use case is I want to log everything related to one hit on the webserver. My nginx creates a uuid (available from 1.11) and adds it to the access log. Then nginx sets the (HTTP_)X-Request-Id header so my application picks it up using this monolog processor adding the request id to my application logs.

**Comment by theofidry** [comment]
I perfectly understand that use case and that's why I said "something along the lines of". If the ID is generated upstream you could inject the request stack and grab it from the header instead of generating it.

That said the above is still incorrect, you need to account for the case where the request doesn't exists (CLI)

**Comment by othillo** [comment]
@theofidry we just tagged 1.0.0

**Comment by theofidry** [comment]
Cheers :)
