### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by raistlin** [qandidate-labs/stack-request-id#9]
Please release a new version 0.4 with Symfony 3 support.

**Comment by zerowebcorp** [comment]
Yes, I am also using symfony 3 and it doesn't support it.

**Comment by robinvdvleuten** [comment]
Yes please 👍

**Comment by othillo** [comment]
there already is a 0.4 release with Symfony 3 support: https://github.com/qandidate-labs/stack-request-id/releases/tag/0.4.0
